orgs:
  redhat-services-platform-team:
    admins:
      - sabre1041
      - tech2734
      - thaas3
      - Tompage1994
    billing_email: thaas@redhat.com
    company: ""
    default_repository_permission: read
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    description: The Red Hat Services Platform Team
    members_can_create_repositories: false
    name: Redhat Services Platform Team
    repos:
      rhel-stig-content:
        description: "RHEL STIG Content"
        default_branch: main
        has_projects: true
        private: true
    members:
      - abenavid
      - andthoma
      - ansiblejunky
      - athias
      - bontreger
      - christophermay07
      - cllebyo
      - curt-matthews
      - david-igou
      - djdanielsson
      - frost-knight
      - Gms-x
      - iamgini
      - ifloresv86
      - jeffmcutter
      - jyamamoto
      - killumslow
      - maford-redhat
      - mdidato
      - stoleas
      - wbentley15
      - wmckinley1
    teams:
      maintainers:
        description: "Organization maintainers"
        privacy: closed
        maintainers:
          - sabre1041
          - tech2734
          - thaas3
          - Tompage1994
        members:
          - djdanielsson
        repos:
          org: write
      americas-spt:
        description: "Americas Ansible SPT"
        privacy: closed
        maintainers:
          - ansiblejunky
          - bontreger
          - killumslow
          - wbentley15
        members:
          - christophermay07
          - cllebyo
          - david-igou
          - ifloresv86
          - jyamamoto
          - mdidato
          - stoleas
          - wmckinley1
        repos:
          ready-to-use-content: write
      americas-spt-admins:
        description: "Americas Ansible SPT Admins"
        privacy: closed
        maintainers:
          - ansiblejunky
          - bontreger
          - killumslow
          - wbentley15
        members: []
        repos:
          ready-to-use-content: admin
      naps-sec:
        description: "NAPS Security Team"
        privacy: closed
        members:
          - andthoma
          - athias
          - curt-matthews
          - frost-knight
          - maford-redhat
        repos:
          rhel-stig-content: write
        teams:
          naps-sec-admins:
            description: "NAPS Security Team Admins"
            privacy: closed
            maintainers:
              - athias
            members: []
            repos:
              rhel-stig-content: admin
