orgs:
  redhat-services-platform-team:
    admins:
      - sabre1041
      - tech2734
      - thaas3
      - Tompage1994
    billing_email: thaas@redhat.com
    company: ""
    default_repository_permission: read
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    description: The Red Hat Services Platform Team
    members_can_create_repositories: false
    name: Redhat Services Platform Team
    repos:
      acl-ready-to-use-content:
        description: "Ansible Content Library - Ready to Use Content"
        default_branch: main
        has_projects: true
        private: true
      ansible-content-library-tooling:
        description: "Ansible Content Library Tooling"
        default_branch: main
        has_projects: true
        private: true
      sellers-ansible-content-tooling:
        description: "Sellers Ansible Content Tooling"
        default_branch: main
        has_projects: true
        private: true
      ansible-amers-ai-standards:
        description: "Americas AI Standards for Ansible"
        default_branch: main
        has_projects: true
        private: true
      ready-to-use-content:
        description: "Previously called starter package. This collection was originally created by the APAC Tech Sales team."
        default_branch: main
        has_projects: true
        private: true
      org:
        description: "Red Hat Services Platform Team GitHub Organization Metadata"
        default_branch: main
        has_projects: true
        private: false
      rhel-stig-content:
        description: "RHEL STIG Content"
        default_branch: main
        has_projects: true
        private: true
    members:
      - abenavid
      - andthoma
      - ansiblejunky
      - athias
      - bontreger
      - christophermay07
      - cllebyo
      - curt-matthews
      - david-igou
      - djdanielsson
      - frost-knight
      - Gms-x
      - iamgini
      - ifloresv86
      - jeffmcutter
      - jyamamoto
      - killumslow
      - maford-redhat
      - mdidato
      - stoleas
      - wbentley15
      - wmckinley1
    teams:
      maintainers:
        description: "Organization maintainers"
        privacy: closed
        maintainers:
          - sabre1041
          - tech2734
          - thaas3
          - Tompage1994
        members:
          - djdanielsson
        repos:
          org: write
      americas-spt:
        description: "Americas Ansible SPT"
        privacy: closed
        maintainers:
          - ansiblejunky
          - bontreger
          - killumslow
          - wbentley15
        members:
          - christophermay07
          - cllebyo
          - david-igou
          - ifloresv86
          - jyamamoto
          - mdidato
          - stoleas
          - wmckinley1
        repos:
          acl-ready-to-use-content: write
          ansible-amers-ai-standards: write
          ready-to-use-content: write
      americas-spt-admins:
        description: "Americas Ansible SPT Admins"
        privacy: closed
        maintainers:
          - ansiblejunky
          - bontreger
          - killumslow
          - wbentley15
        members: []
        repos:
          acl-ready-to-use-content: admin
          ansible-amers-ai-standards: admin
          ready-to-use-content: admin
      ansible-content-library-tooling:
        description: "Ansible Content Library Tooling Team"
        privacy: closed
        maintainers:
          - stoleas
          - wmckinley1
        members:
          - ansiblejunky
        repos:
          ansible-content-library-tooling: write
          sellers-ansible-content-tooling: write
        teams:
          ansible-content-library-tooling-admins:
            description: "Ansible Content Library Tooling Admins"
            privacy: closed
            maintainers:
              - stoleas
              - wmckinley1
            members: []
            repos:
              ansible-content-library-tooling: admin
              sellers-ansible-content-tooling: admin
      naps-sec:
        description: "NAPS Security Team"
        privacy: closed
        members:
          - andthoma
          - athias
          - curt-matthews
          - frost-knight
          - maford-redhat
        repos:
          rhel-stig-content: write
        teams:
          naps-sec-admins:
            description: "NAPS Security Team Admins"
            privacy: closed
            maintainers:
              - athias
            members: []
            repos:
              rhel-stig-content: admin
